[versions]
agp = "8.7.3"
androidTools = "31.8.0"
datastorePreferences = "1.1.2"
playFeatureDelivery = "2.1.0"
coreSplashscreen = "1.0.1"
coilCompose = "2.7.0"
desugar_jdk_libs = "2.1.4"
kotlin = "2.1.0"
coreKtx = "1.15.0"
activityCompose = "1.10.0"
ktor = "3.0.1"
ktorClientLogging = "3.0.1"
koin = "4.0.0"
lifecycleRuntimeKtx = "2.8.7"
composeBom = "2025.01.00"
materialIconsExtended = "1.7.6"
navigationCompose = "2.8.5"
securityCryptoKtx = "1.1.0-alpha06"
timber = "5.0.1"
ksp = "2.1.0-1.0.29"
room = "2.6.1"
appcompat = "1.7.0"
material = "1.12.0"
org-jetbrains-kotlin-jvm = "2.1.0"
maps = "4.3.3"
coroutines = "1.9.0"
gmsLocation = "21.3.0"
mapsUtils = "5.0.0"
bson = "4.11.1"
work = "2.10.0"
kotlinx-serialization = "1.7.3"
secretsPlugin = "2.0.1"
playServicesMaps = "19.0.0"
annotation = "1.9.1"
composeWearOs = "1.4.0"
composeMaterialWearOs = "1.0.0-alpha31"
health = "1.0.0-rc02"
play-services-wearable = "19.0.0"
wear = "1.3.0"

# Testing
androidx-arch = "2.2.0"
androidx-test = "1.6.1"
androidx-test-monitor = "1.7.2"
androidx-work-test = '2.10.0'
coroutines-test = "1.8.1"
espresso = "3.6.1"
fragment-test = "1.8.5"
junit-test = "1.2.1"
junit5 = '5.10.1'
konsist = "0.15.1"
mockito = "5.6.0"
mockito-inline = "5.2.0"
mockito-kotlin = "5.1.0"
mockk = "1.13.12"
test-parameter-injector = "1.18"
truth = "1.4.2"
turbine = "1.0.0"
roboelectric = "4.14"
room-test = "2.6.1"
runner = "1.6.2"

# Project versions
projectApplicationId = "com.joeji.currencyconversionapp"
projectVersionName = "1.0"
projectMinSdkVersion = "26"
projectTargetSdkVersion = "35"
projectCompileSdkVersion = "35"
projectVersionCode = "1"
junit = "4.13.2"
junitVersion = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "securityCryptoKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
play-feature-delivery = { module = "com.google.android.play:feature-delivery", version.ref = "playFeatureDelivery" }
play-feature-delivery-ktx = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "playFeatureDelivery" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
koin-android-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-maps-android-compose = { module = "com.google.maps.android:maps-compose", version.ref = "maps" }
google-android-gms-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "gmsLocation" }
org-mongodb-bson = { module = "org.mongodb:bson", version.ref = "bson" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
google-maps-android-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "mapsUtils" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-wear-compose-material = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterialWearOs" }
androidx-wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeWearOs" }
androidx-wear-compose-ui-tooling = { group = "androidx.wear.compose", name = "compose-ui-tooling", version.ref = "composeWearOs" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "play-services-wearable" }
androidx-health-services-client = { group = "androidx.health", name = "health-services-client", version.ref = "health" }
androidx-wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }

# Test
arch-core-test = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }
fragment-test = { module = "androidx.fragment:fragment-testing", version.ref = "fragment-test" }
junit-test-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-test" }
junit5-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito-inline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-monitor = { module = "androidx.test:monitor", version.ref = "androidx-test-monitor" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-parameter-injector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-parameter-injector" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
truth-ext = { module = "androidx.test.ext:truth", version.ref = "androidx-test" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "roboelectric" }
room-test = { module = "androidx.room:room-testing", version.ref = "room-test" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-work-test = { module = "androidx.work:work-testing", version.ref = "androidx-work-test" }

# Gradle
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
androidDynamicFeature = { id = "com.android.dynamic-feature", version.ref = "agp" }
mapsplatform-secrets-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsPlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

currencyconversionapp-android-application = { id = "currencyconversionapp.android.application", version = "unspecified" }
currencyconversionapp-android-application-compose = { id = "currencyconversionapp.android.application.compose", version = "unspecified" }
currencyconversionapp-android-library = { id = "currencyconversionapp.android.library", version = "unspecified" }
currencyconversionapp-android-library-compose = { id = "currencyconversionapp.android.library.compose", version = "unspecified" }
currencyconversionapp-android-feature-ui = { id = "currencyconversionapp.android.feature.ui", version = "unspecified" }
currencyconversionapp-android-room = { id = "currencyconversionapp.android.room", version = "unspecified" }
currencyconversionapp-android-dynamic-feature = { id = "currencyconversionapp.android.dynamic.feature", version = "unspecified" }
currencyconversionapp-jvm-library = { id = "currencyconversionapp.jvm.library", version = "unspecified" }
currencyconversionapp-jvm-ktor = { id = "currencyconversionapp.jvm.ktor", version = "unspecified" }
currencyconversionapp-android-test = { id = "currencyconversionapp.android.test", version = "unspecified" }
currencyconversionapp-jvm-test = { id = "currencyconversionapp.jvm.test", version = "unspecified" }
currencyconversionapp-android-application-wear-compose = { id = "currencyconversionapp.android.application.wear.compose", version = "unspecified" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
]
compose-debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest",
]
koin = ["koin-core", "koin-android", "koin-android-workmanager"]
koin-compose = ["koin-core", "koin-android", "koin-android-workmanager", "koin-androidx-compose"]
ktor = [
    "ktor-client-auth",
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json"
]
#Test
unit-test = ["truth", "mockito", "mockito-inline", "mockito-kotlin", "turbine", "mockk", "konsist", "coroutines-test"]
ui-test = ["roboelectric", "espresso-core", "espresso-intents", "mockk-android"]
junit5-api = ["junit-jupiter", "junit-jupiter-api", "junit-vintage-engine", "junit-jupiter-params"]